spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://39.106.49.196:3306/pms_java?characterEncoding=utf8
    username: WZC
    password: WZC000
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 最大活跃数
    maxActive: 20
    # 初始化数量
    initialSize: 1
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerconnectionSize: 20
    # mergeSql = StatFilter提供合并的功能, 通过connectionProperties属性来打开mergeSql功能；慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    # 是否检测空闲连接超时，由timeBetweenEvictionRunsMillis控制超时时间
    testWhileIdle: true
    # 检测sql有效性，会降低性能
    testOnBorrow: false
    # 检测sql有效性，会降低性能
    testOnReturn: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/ # jsp路径支持
      suffix: .jsp

  #配置redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0 #默认是索引为0的数据库





#2018-02-04 初始demo版本 换成 log4jdbc后可以查看完整参数输出
#spring:
#  datasource:
##    url: jdbc:mysql://39.106.49.196:3306/pms_java?characterEncoding=utf8
#    url: jdbc:log4jdbc:mysql://39.106.49.196:3306/pms_java?characterEncoding=utf8
##    driverClassName: com.mysql.jdbc.Driver
#    driverClassName: net.sf.log4jdbc.DriverSpy
#    username: wzc
#    password: wzc
#  jpa:
#    database: MySQL
#    show-sql: true
#    hibernate:
##      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

